### ISSUE TITLE
Broken build on Ubuntu 14.04 (trusty)

### ISSUE THREAD

**Issue by nantiferov** [dawidd6/action-debian-package#26]
Hello,

Thank you for this GitHub action, it's pretty easy and nice to use 😊.

I know that this OS is quite outdated, but I tried to build deb package for Ubuntu 14.04 (trusty) with your action and got error at `Install build dependencies` stage. It seems that apt-get in old Ubuntu is unable to detect that it's a local package and wants to find information about package in `deb-src` repos.

```
Install build dependencies
  /usr/bin/docker exec package_name apt-get build-dep -yq -t trusty /home/runner/work/dir/dir/package_name
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: You must put some 'source' URIs in your sources.list
```

Seems that there is no other way to force to apt-get to just read local `DEBIAN/control`.

I tested it locally and I think that could be kinda fixed just by skipping this step. `dpkg-buildpackage` is building package successfully cause I don't have much build-time dependencies and they're installed during previous step `apt-get install -yq -t trusty dpkg-dev debhelper devscripts`.
Or parsing of `Build-Depends` could be added to action.

The same package build is successful for Ubuntu 16.04/18.04.

I can prepare PR with skipping `apt-get build-dep` step for Ubuntu 14.04.

**Comment by dawidd6** [comment]
PR would be great.

**Comment by nantiferov** [comment]
Tested on my fork, build passes on Ubuntu 14.04

**Comment by nantiferov** [comment]
@dawidd6 what do you think about add option to define OS as option to action?
Now it gets from `debian/changelog`, but for example if we want to build package from one source for different OS, we have to either keep duplicated folders or change `debian/changelog` with something like sed before action run.

I can prepare PR for that.

**Comment by dawidd6** [comment]
No need for `sed`. There is an utility called `dch` for exactly this purpose. But yes, this feature is on my TODO list nevertheless, so a PR would be great. Thanks.

**Comment by nantiferov** [comment]
Oh, thanks, didn't know about `dch `, will check it.
As well as prepare PR, probably this week.
