### ISSUE TITLE
pwd doesn't look like a git repository ..

### ISSUE THREAD

**Issue by waja** [dawidd6/action-debian-package#62]
Hi,

at first thanks for you work on this nice piece of software.

I discovered that `git-deborig HEAD` is failing for some repositories. It is also [reproducible](https://github.com/dawidd6/action-debian-package/actions/runs/3335759097/jobs/5520103192#step:4:4542) in you CI pipeline.

Thanks, Jan

**Comment by dawidd6** [comment]
Yes, I saw it, but I don't know how to fix it yet. It worked before :confused:

**Comment by dawidd6** [comment]
Would appreciate some help :)

**Comment by waja** [comment]
I#ll have a look into it hopefully until next weekend
