### ISSUE TITLE
lintian support lost from master?

### ISSUE THREAD

**Issue by SebKuzminsky** [dawidd6/action-debian-package#68]
It looks like master was reset earlier today, and a couple of lintian-related commits were lost (52e8860d4f84b90b300d5f593b8d6510fd4c4b14 and b0c83f2a4e795ed99a384dd182bc617dd12d8fc9).

Was that intentional?

I saved a pointer to the old master head at https://github.com/SebKuzminsky/action-debian-package/tree/lintian

**Comment by dawidd6** [comment]
Ooops, sorry, added back. Thanks for heads up!
