### ISSUE TITLE
pwd doesn't look like a git repository ..

### ISSUE THREAD

**Issue by ennorehling** [dawidd6/action-debian-package#72]
I'm getting this error message when building a Debian packages for my project.

```
Run dawidd6/action-debian-package@v1.4.4
> Get image name
> Print details
> Create container
> Start container
> Prepare environment
> Update packages list
> Install development packages
> Trust this git repo
> Install build dependencies
v Create tarball
  /usr/bin/docker exec csmapfx git-deborig HEAD
  pwd doesn't look like a git repository ..
  Error: The process '/usr/bin/docker' failed with exit code 128
```

The full job log in question is here:
https://github.com/ennorehling/csmapfx/actions/runs/3719532423/jobs/6308448425

**Comment by ennorehling** [comment]
There is a long-ish explanation in the commit message for 0181a8bea44aa348993a3d77a9cdce7a59c4f709 claiming this is a problem with running git as root, and proposing a fix, "tell git to trust the repo", but that fix doesn't seem to work here.

**Comment by waja** [comment]
Same for me ... I'm still [facing](https://github.com/waja/nagios-snmp-plugins/actions/runs/3910475715/jobs/6682722463) this issue (again) in recent builds, while was working [well a month ago](https://github.com/waja/nagios-snmp-plugins/actions/runs/3693792264/jobs/6254203465). All those jobs were using `dawidd6/action-debian-package@v1.4.4` and it is not limited to one repo, but affects all of my (recent) pipelines.

**Comment by waja** [comment]
it seems something different then #62

**Comment by waja** [comment]
Maybe it's worth to try another approach?

https://github.com/pi-top/debian-package-build-action is using 
https://github.com/pi-top/debian-package-build-action/blob/master/docker_base/scripts/build/build-deb.sh#L39-L58 to create the tarball

**Comment by dawidd6** [comment]
Thanks @waja, looks like it works now!
